
setxkbmap pl &
nitrogen --set-zoom-fill --random &
picom &
unclutter &
xrdb ~/.Xresources &
# xrdb -merge ~/.Xresources &
#transmission-daemon &
#`
# exec dwm
# exec startlxqt #with herbstluft as window manager
# exec spectrwm
#exec herbstluftwm
# exec pekwm
# exec openbox
exec i3
# exec startplasma-x11
# exec fvwm
# exec jwm
# exec awesome
# exec qtile
# exec icewm-session
# exec cinnamon-session
# # exec mate-session
# exec xfce4-session
