#!/bin/bash

sleep 1 &&
nitrogen --set-zoom-fill --random &
sleep 1 &&
transmission-init.sh &
sleep 1 &&
dtach -n cmux cmus &
# # start network manager */
#     sleep 1 && */
#     nm-applet & */

# # enable bluetooth applet */
#     sleep 1 && */
#     blueman-applet &! */

# # enable screensaver */
#     xscreensaver -nosplash & */

# # start redshift */
#     redshift & */

# # enable lockscreen */
#     exec xautolock -detectsleep -time 15 -locker "i3lock -n -i /home/user/lockscreen.png" -killtime 20 -killer "systemctl suspend" #lock after inactivity and then sleep */

# # allow notifications */
#     /usr/lib/notification-daemon-1.0/notification-daemon & */
