#!/usr/bin/env bash

# this is a simple config for herbstluftwm

hc() {
    herbstclient "$@"
}

hc emit_hook reload

xsetroot -solid '#5A8E3A'

### AUTOSTART ###
# dtach -n cmux cmus &
# picom &
audacious -p &
transmission-init.sh &
nitrogen --set-zoom-fill --random
# volumeicon
# trayer --padding 2 --tint 0x222222 --transparent true --edge top --edge right

# remove all existing keybindings
hc keyunbind --all

# keybindings
# if you have a super key you will be much happier with Mod set to Mod4
Mod=Mod4   # Use the super key as the main modifier
myTerm=st

hc keybind $Mod-Shift-q quit
hc keybind $Mod-Shift-r reload
hc keybind $Mod-q close
# hc keybind $Mod-Shift-Return spawn $myTerm
# hc keybind $Mod-Shift-Return spawn "${myTerm:-xterm}" # use your $TERMINAL with xterm as fallback
hc keybind $Mod-Shift-Return spawn "${TERMINAL:-xterm}" # use your $TERMINAL with xterm as fallback

# basic movement in tiling and floating mode
# focusing clients
hc keybind $Mod-Left  focus left
hc keybind $Mod-Down  focus down
hc keybind $Mod-Up    focus up
hc keybind $Mod-Right focus right
hc keybind $Mod-h     focus left
hc keybind $Mod-j     focus down
hc keybind $Mod-k     focus up
hc keybind $Mod-l     focus right

# moving clients in tiling and floating mode
hc keybind $Mod-Shift-Left  shift left
hc keybind $Mod-Shift-Down  shift down
hc keybind $Mod-Shift-Up    shift up
hc keybind $Mod-Shift-Right shift right
hc keybind $Mod-Shift-h     shift left
hc keybind $Mod-Shift-j     shift down
hc keybind $Mod-Shift-k     shift up
hc keybind $Mod-Shift-l     shift right

# splitting frames
# create an empty frame at the specified direction
hc keybind $Mod-u       split   bottom  0.5
hc keybind $Mod-o       split   right   0.5
# let the current frame explode into subframes
hc keybind $Mod-e split explode

# resizing frames and floating clients
resizestep=0.02
hc keybind $Mod-Control-h       resize left +$resizestep
hc keybind $Mod-Control-j       resize down +$resizestep
hc keybind $Mod-Control-k       resize up +$resizestep
hc keybind $Mod-Control-l       resize right +$resizestep
hc keybind $Mod-Control-Left    resize left +$resizestep
hc keybind $Mod-Control-Down    resize down +$resizestep
hc keybind $Mod-Control-Up      resize up +$resizestep
hc keybind $Mod-Control-Right   resize right +$resizestep

# tags
tag_names=( {1..9} )
tag_keys=( {1..9} 0 )

hc rename default "${tag_names[0]}" || true
for i in "${!tag_names[@]}" ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

# cycle through tags
hc keybind $Mod-period use_index +1 --skip-invisible
hc keybind $Mod-comma  use_index -1 --skip-invisible
hc keybind $Mod-a  use_previous

# layouting
hc keybind $Mod-r remove
hc keybind $Mod-Shift-t floating toggle
hc keybind $Mod-t set_attr clients.focus.floating toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-d pseudotile toggle
# The following cycles through the available layouts within a frame, but skips
# layouts, if the layout change wouldn't affect the actual window positions.
# I.e. if there are two windows within a frame, the grid layout is skipped.
hc keybind $Mod-space                                                           \
            or , and . compare tags.focus.curframe_wcount = 2                   \
                     . cycle_layout +1 vertical horizontal max vertical grid    \
               , cycle_layout +1

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# focus
hc keybind $Mod-BackSpace   cycle_monitor
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1
hc keybind $Mod-c cycle
hc keybind $Mod-i jumpto urgent

# theme
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc set frame_border_active_color '#b200b2'
hc set frame_border_normal_color '#282828'
hc set frame_bg_normal_color '#565656'
hc set frame_bg_active_color '#345F0C'
hc set frame_border_width 1
hc set always_show_frame on
hc set frame_bg_transparent on
hc set frame_transparent_width 1
hc set frame_gap 1

# hc attr theme.active.color '#9fbc00'
hc attr theme.active.color '#FFFFFF'
hc attr theme.normal.color '#454545'
hc attr theme.urgent.color orange
hc attr theme.inner_width 1
hc attr theme.inner_color black
hc attr theme.border_width 3
hc attr theme.floating.border_width 4
hc attr theme.floating.outer_width 1
hc attr theme.floating.outer_color black
hc attr theme.active.inner_color '#3E4A00'
hc attr theme.active.outer_color '#3E4A00'
hc attr theme.background_color '#141414'

hc set window_gap 0
hc set frame_padding 1
hc set smart_window_surroundings off
hc set smart_frame_surroundings on
hc set mouse_recenter_gap 0

# rules
hc unrule -F
#hc rule class=XTerm tag=3 # move all xterms to tag 3
hc rule focus=on # normally focus new clients
#hc rule focus=off # normally do not focus new clients
# give focus to most common terminals
#hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' floating=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

hc set tree_style '╾│ ├└╼─┐'

# unlock, just to be sure
hc unlock

# do multi monitor setup here, e.g.:
# hc set_monitors 1280x1024+0+0 1280x1024+1280+0
# or simply:
# hc detect_monitors

# find the panel
# panel="$SCRIPTS/panel.sh"
# panel=/usr/bin/barpyrus turned off for lxqt
panel="$SCRIPTS/polybar.sh" 
[ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
for monitor in $(hc list_monitors | cut -d: -f1) ; do
    # start it on each monitor
    "$panel" "$monitor" &
done

### CUSTOM KEYBINDINGS AND STUFF ###
hc set focus_follows_mouse on
hc set hide_covered_windows on

### MY KEYBINDINGS ###
# Misc
hc keybind Mod1-g 		spawn steam
hc keybind Mod1-Shift-t 	spawn teamspeak3
hc keybind Mod1-v 		spawn qutebrowser "qute://settings"
hc keybind Mod1-Shift-v 	spawn vimb
hc keybind Mod1-w 		spawn palemoon
hc keybind Mod1-Shift-n 	spawn nitrogen --set-zoom-fill --random
hc keybind Ctrl-Mod1-t 		spawn $myTerm -e dtach -A dvtx dvtm -M
# hc keybind Mod1-l 		spawn $myTerm -e lf
# hc keybind Mod1-l 		spawn $myTerm -e dvtm -m ^z -M f
hc keybind Mod1-d 		spawn $myTerm -e stig
hc keybind Mod1-r 		spawn redshift -b 0.95 -O 5000K
hc keybind Mod1-Shift-r 	spawn redshift -x
hc keybind Mod1-e 		spawn emacsclient -a "" -c
hc keybind Mod1-F11	 	spawn $myTerm -e bpytop
hc keybind F12	 		spawn qalculate-gtk
# hc keybind Button8 		spawn xmenu.sh
hc keybind Mod1-F9 		spawn $myTerm -e dtach -A aerx aerc

# Screen capture
hc keybind Print 		spawn flameshot gui
hc keybind $Mod-Print 		spawn screenshot.sh full
hc keybind Mod1-Print 		spawn screenshot.sh 16x9
hc keybind Mod1-Shift-Print	spawn screenshot.sh 4x3
hc keybind Mod1-Shift-c 	spawn screenshot.sh select
hc keybind Mod1-c		spawn screenshot.sh clipboard


# rofi
# hc keybind Mod1-p spawn rofi -modi "run,ssh" -show run
hc keybind $Mod-p 		spawn ~/.config/herbstluftwm/dmenu_run_hlwm
hc keybind Mod1-p 		spawn rofi -show drun -show-icons
hc keybind Mod1-F11 		spawn rofimoji -action clipboard
hc keybind Mod1-F12 		spawn rofi -show calc -modi "calc:qalc +u8 -nocurrencies"
hc keybind $Mod-Shift-p 	spawn rofi -show

# Audio
hc keybind Mod1-a 		spawn $myTerm -e pulsemixer
hc keybind $Mod-F2 		spawn pamixer --decrease 2
hc keybind $Mod-F3 		spawn pamixer --increase 2
hc keybind $Mod-F4 		spawn pamixer --toggle-mute

hc keybind Mod1+F1 		spawn audacious -m
hc keybind Mod1+F2 		spawn audtool --set-volume -2% # vol dec
hc keybind Mod1+F3 		spawn audtool --set-volume +2% # vol inc
hc keybind Mod1+Shift+F5	spawn audtool --playlist-toggle-shuffle # shuffle toggle
hc keybind Mod1+F5 		spawn audtool --playback-stop # stop
hc keybind Mod1+F6 		spawn audtool --playlist-reverse # prev toggle
hc keybind Mod1+F7 		spawn audtool --playback-pause & audacious-notify.sh # play toggle
hc keybind Mod1+F8 		spawn audtool --playlist-advance # next

# hc keybind Mod1-F1 		spawn $myTerm -e ncmpcpp
# hc keybind Mod1-F2 		spawn mpc volume -2
# hc keybind Mod1-F3 		spawn mpc volume +2
# hc keybind Mod1-F5 		spawn mpc stop
# hc keybind Mod1-F6 		spawn mpc prev
# hc keybind Mod1-F7 		spawn mpc toggle
# hc keybind Mod1-F8 		spawn mpc next

# ### LAPTOP ###
# hc keybind $Mod-F2 		spawn xbacklight -dec 2
# hc keybind $Mod-F3 		spawn xbacklight -inc 1
# hc keybind $Mod-F6 		spawn pamixer --toggle-mute
# hc keybind $Mod-F7 		spawn pamixer --decrease 2
# hc keybind $Mod-F8 		spawn pamixer --increase 1
# hc keybind Mod1-F7 		spawn cmus-remote --volume -2%
# hc keybind Mod1-F8 		spawn cmus-remote --volume +2%
# hc keybind Mod1-F9 		spawn music_manager.sh prev
# hc keybind Mod1-F10 		spawn music_manager.sh toggle
# hc keybind Mod1-F11 		spawn music_manager.sh next
# hc keybind XF86AudioRaiseVolume spawn pamixer --decrease 2
# hc keybind XF86AudioLowerVolume spawn pamixer --increase 1


# MY KEYBINDINGS ###
hc keybind $mod+Shift+Tab	focus left
hc keybind $mod+Tab		focus right
hc keybind $mod+x			spawn xkill
hc keybind Mod1+l			spawn i3lock-wrapper
hc keybind $Mod+b			spawn polybar-msg cmd toggle
# Misc
hc keybind Mod1+g			spawn steam
hc keybind Mod1+Shift+t	spawn teamspeak3
hc keybind Mod1+Shift+v 	spawn qutebrowser "qute://settings"
hc keybind Mod1+v 			spawn vimb
hc keybind Mod1+w			spawn palemoon
hc keybind Mod1+Shift+n 	spawn nitrogen --set-zoom-fill --random
hc keybind Mod1+Ctrl+t 	spawn $myTerm -e dtach -A /tmp/dvtx dvtm -m  -M f
hc keybind Mod1+Ctrl+l		spawn $myTerm -e dtach -A /tmp/ffx fff
hc keybind Mod1+d 			spawn $myTerm -e stig
hc keybind Mod1+r 			spawn redshift -b 0.95 -O 5000K
hc keybind Mod1+Shift+r 	spawn redshift -x
hc keybind Mod1+e 			spawn emacsclient -a "" -c
hc keybind Mod1+f 			spawn rox
# Screen capture
hc keybind Print			spawn flameshot gui
hc keybind $Mod+Print		spawn screenshot.sh full
hc keybind $Mod+Shift+Print spawn screenshot.sh focused
hc keybind Mod1+Shift+c	spawn screenshot.sh select
hc keybind Mod1+c			spawn screenshot.sh clipboard
hc keybind Mod1+1			spawn screenshot.sh 16x9
hc keybind Mod1+4			spawn screenshot.sh 4x3
# Audio
hc keybind $Mod+F2 		spawn pamixer --decrease 2
hc keybind $Mod+F3 		spawn pamixer --increase 2
hc keybind $Mod+F4 		spawn pamixer --toggle-mute
hc keybind Mod1+a			spawn $myTerm -e pulsemixer
hc keybind Mod1+F1 		spawn audacious -m
hc keybind Mod1+F2 		spawn audtool --set-volume -2% # vol dec
hc keybind Mod1+F3 		spawn audtool --set-volume +2% # vol inc
hc keybind Mod1+Shift+F5	spawn audtool --playlist-toggle-shuffle # shuffle toggle
hc keybind Mod1+F5 		spawn audtool --playback-stop # stop
hc keybind Mod1+F6 		spawn audtool --playlist-reverse # prev toggle
hc keybind Mod1+F7 		spawn audtool --playback-pause && audacious-notify.sh # play toggle
hc keybind Mod1+F8 		spawn audtool --playlist-advance # next
hc keybind Mod1+F9			spawn $myTerm -e dtach -A /tmp/aerx aerc
hc keybind Mod1+F11		spawn $myTerm -e bpytop
hc keybind Mod1+F12		spawn $myTerm -e qalc
hc keybind Mod1+Shift+F12	spawn qalculate-gtk
